CREATE TABLE `dtcc` (
  `DISSEMINATION_ID` int(20) NOT NULL PRIMARY KEY,
  `ORIGINAL_DISSEMINATION_ID` int(20) DEFAULT NULL,
  `ACTION` varchar(15) DEFAULT NULL,
  `EXECUTION_TIMESTAMP` varchar(20) DEFAULT NULL,
  `CLEARED` varchar(5) DEFAULT NULL,
  `INDICATION_OF_COLLATERALIZATION` varchar(2) DEFAULT NULL,
  `INDICATION_OF_END_USER_EXCEPTION` varchar(1) DEFAULT NULL,
  `INDICATION_OF_OTHER_PRICE_AFFECTING_TERM` varchar(1) DEFAULT NULL,
  `BLOCK_TRADES_AND_LARGE_NOTIONAL_OFF-FACILITY_SWAPS` varchar(5) DEFAULT NULL,
  `EXECUTION_VENUE` varchar(15) DEFAULT NULL,
  `EFFECTIVE_DATE` varchar(12) DEFAULT NULL,
  `END_DATE` varchar(12) DEFAULT NULL,
  `DAY_COUNT_CONVENTION` varchar(20) DEFAULT NULL,
  `SETTLEMENT_CURRENCY` varchar(8) DEFAULT NULL,
  `ASSET_CLASS` varchar(5) DEFAULT NULL,
  `SUB-ASSET_CLASS_FOR_OTHER_COMMODITY` varchar(20) DEFAULT NULL,
  `TAXONOMY` varchar(70) DEFAULT NULL,
  `PRICE_FORMING_CONTINUATION_DATA` varchar(15) DEFAULT NULL,
  `UNDERLYING_ASSET_1` varchar(100) DEFAULT NULL,
  `UNDERLYING_ASSET_2` varchar(100) DEFAULT NULL,
  `PRICE_NOTATION_TYPE` varchar(15) DEFAULT NULL,
  `PRICE_NOTATION` varchar(15) DEFAULT NULL,
  `ADDITIONAL_PRICE_NOTATION_TYPE` varchar(8) DEFAULT NULL,
  `ADDITIONAL_PRICE_NOTATION` varchar(15) DEFAULT NULL,
  `NOTIONAL_CURRENCY_2` varchar(8) DEFAULT NULL,
  `ROUNDED_NOTIONAL_AMOUNT_1` varchar(15) DEFAULT NULL,
  `ROUNDED_NOTIONAL_AMOUNT_2` varchar(15) DEFAULT NULL,
  `PAYMENT_FREQUENCY_1` varchar(20) DEFAULT NULL,
  `PAYMENT_FREQUENCY_2` varchar(20) DEFAULT NULL,
  `RESET_FREQUENCY_1` varchar(20) DEFAULT NULL,
  `RESET_FREQUENCY_2` varchar(20) DEFAULT NULL,
  `EMBEDED_OPTION` varchar(10) DEFAULT NULL,
  `OPTION_STRIKE_PRICE` varchar(15) DEFAULT NULL,
  `OPTION_TYPE` varchar(5) DEFAULT NULL,
  `OPTION_FAMILY` varchar(8) DEFAULT NULL,
  `OPTION_CURRENCY` varchar(8) DEFAULT NULL,
  `OPTION_PREMIUM` varchar(15) DEFAULT NULL,
  `OPTION_LOCK_PERIOD` varchar(20) DEFAULT NULL,
  `OPTION_EXPIRATION_DATE` varchar(12) DEFAULT NULL,
  `PRICE_NOTATION2_TYPE` varchar(8) DEFAULT NULL,
  `PRICE_NOTATION2` varchar(12) DEFAULT NULL,
  `PRICE_NOTATION3_TYPE` varchar(8) DEFAULT NULL,
  `PRICE_NOTATION3` varchar(12) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `NEWEST_DATE`;
CREATE TABLE `NEWEST_DATE` (
  `NAME` VARCHAR(20) NOT NULL PRIMARY KEY,
  `DATE` VARCHAR(12) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1


CREATE TABLE `COM/SWAP` (
  `ACTION` varchar(15) DEFAULT NULL,
  `TAXONOMY` varchar(70) NOT NULL PRIMARY KEY,
  `EXECUTION_TIMESTAMP` varchar(20) DEFAULT NULL,
  `UNDERLYING_ASSET_1` varchar(100) DEFAULT NULL,
  `UNDERLYING_ASSET_2` varchar(100) DEFAULT NULL,
  `END_DATE` varchar(12) DEFAULT NULL,
  `ROUNDED_NOTIONAL_AMOUNT_1` varchar(15) DEFAULT NULL,
  `NOTIONAL_CURRENCY_1` varchar(8) DEFAULT NULL,
  `CLEARED` varchar(5) DEFAULT NULL,
  `PRICE_NOTATION` varchar(15) DEFAULT NULL,
  `PRICE_NOTATION_TYPE` varchar(15) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `COM/OPTION` (
  `ACTION` varchar(15) DEFAULT NULL,
  `TAXONOMY` varchar(70) NOT NULL PRIMARY KEY,
  `EXECUTION_TIMESTAMP` varchar(20) DEFAULT NULL,
  `OPTION_TYPE` varchar(5) DEFAULT NULL,
  `UNDERLYING_ASSET_1` varchar(100) DEFAULT NULL,
  `UNDERLYING_ASSET_2` varchar(100) DEFAULT NULL,
  `EFFECTIVE_DATE` varchar(12) DEFAULT NULL,
  `END_DATE` varchar(12) DEFAULT NULL,
  `ROUNDED_NOTIONAL_AMOUNT_1` varchar(15) DEFAULT NULL,
  `NOTIONAL_CURRENCY_1` varchar(8) DEFAULT NULL,
  `CLEARED` varchar(5) DEFAULT NULL,
  `OPTION_STRIKE_PRICE` varchar(15) DEFAULT NULL,
  `PRICE_NOTATION_TYPE` varchar(15) DEFAULT NULL,
  `OPTION_PREMIUM` varchar(15) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;